src/Entity/Reservation.php
<?php

namespace App\Entity;
use App\Entity\Client;
use App\Repository\ReservationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'datetime')]
    #[Assert\GreaterThan('today', message:"Ce créneau ne peut pas être réservé.")]
    private $heure_de_rendez_vous;

    #[ORM\Column(type: 'string')]
    private $status;

    #[ORM\ManyToOne(targetEntity: Client::class, inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private $id_client;

    #[ORM\ManyToOne(targetEntity: Client::class, inversedBy: 'appointment')]
    #[ORM\JoinColumn(nullable: false)]
    private $pro;

    #[ORM\ManyToOne(targetEntity: Prestation::class, inversedBy: 'reservations')]
    #[ORM\JoinColumn(nullable: false)]
    private $prestation;

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeureDeRendezVous(): ?\DateTimeInterface
    {
        return $this->heure_de_rendez_vous;
    }

    public function setHeureDeRendezVous(\DateTimeInterface $heure_de_rendez_vous): self
    {
        $this->heure_de_rendez_vous = $heure_de_rendez_vous;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getIdClient(): ?Client
    {
        return $this->id_client;
    }

    public function setIdClient(?Client $id_client): self
    {
        $this->id_client = $id_client;

        return $this;
    }

    public function getPro(): ?Client
    {
        return $this->pro;
    }

    public function setPro(?Client $pro): self
    {
        $this->pro = $pro;

        return $this;
    }

    public function getPrestation(): ?Prestation
    {
        return $this->prestation;
    }

    public function setPrestation(?Prestation $prestation): self
    {
        $this->prestation = $prestation;

        return $this;
    }
}

src/Form/UtilisateurType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UtilisateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstname', TextType::class, [
                'label' => 'Prénom',
            ])
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'required' => false,
                'invalid_message' => 'The password fields must match.',
                'invalid_message_parameters' => ['first_options' == 'second_options'],
                'options' => ['attr' => ['class' => 'password-field']],
                'first_options'  => ['label' => 'Password'],
                'second_options' => ['label' => 'Repeat Password'],
                'empty_data' => '',
                'mapped' => false,
            ])
            ->add('lastname')
            ->add('email', EmailType::class)
            ->add('date_de_naissance', BirthdayType::class, [
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
            ])
            ->add('genre', ChoiceType::class, [
                'choices' => [
                    'Femme' => 'Femme',
                    'Homme' => 'Homme'
                ],
                // 'choice_label' => 'genre',
                'expanded' => true,
                'multiple' => false,
            ])
            /* ->get('genre')->addModelTransformer(new CallbackTransformer(
                // transform the array to a string
                function ($genreAsArray) {
                    return implode(', ', $genreAsArray);
                },
                // transform the string back to an array
                function ($genreAsString) {
                    return explode(', ', $genreAsString);
                }
            )) */
            ->add('adresse', TextareaType::class) // utiliser l'api : https://api-adresse.data.gouv.fr/search/?q=nomdevotreadresse
            ->add('code_postal', IntegerType::class)
            ->add('ville', TextType::class)
            ->add('promotions', CheckboxType::class, [
                'label' => 'Recevoir les messages promotionnels',
                'required' => false,
            ])
            ->add('alerteSMS', CheckboxType::class, [
                'label' => 'Recevoir les alertes SMS',
                'required' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/UtilisateurController.php
<?php

namespace App\Controller;

use App\Form\UtilisateurType;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class UtilisateurController extends AbstractController
{
    #[Route('/utilisateur', name: 'app_utilisateur')]
    public function index(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $userPasswordHasher, ReservationRepository $reservation): Response
    {
        $events = [];
        $rdvs = [];
        foreach ($events as $event) {
            $rdvs[] = [
                'id' => $event->getId(),
                'title' => $event->getTitle(),
                'start' => $event->getStart()->format('Y-m-d H:i:s'),
                'end' => $event->getEnd()->format('Y-m-d H:i:s'),
                'description' => $event->getDescription(),
                'allDay' => $event->isAllDay(),
                'backgroundColor' => $event->getBackgroundColor(),
                'borderColor' => $event->getBorderColor(),
                'textColor' => $event->getTextColor(),
            ];
        }
        $data = json_encode($rdvs);
        // dump($data);
        $utilisateur = $this->getUser();
        $reservations = $reservation->findBy([
            'id_client' => $utilisateur 
        ]);
        $professionels = $reservation->findBy([
            'pro' => $utilisateur
        ]);
        // dd($professionels);
        // dd($reservation);
        // dd($utilisateur);
        $form = $this->createForm(UtilisateurType::class, $utilisateur);
        // dd($form);
        //$password = $form->getData()->getPassword();
        //dump($password);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $utilisateur = $form->getData();
            $password = $form->getData()->getPassword();
            // dd(strlen($password));
            // dd($form->getData('password'));
            $modifiedPassword = $form->get('password')->getData();
            if ($modifiedPassword != null) {
                $utilisateur->setPassword(
                    $userPasswordHasher->hashPassword(
                        $this->getUser(),
                        $form->get('password')->getData()
                    )
                );
            } else {
                $utilisateur->setPassword($password);
            }
            $entityManager->persist($utilisateur);
            $entityManager->flush();
            $this->addFlash('success', 'Vos informations ont été modifiées avec succès');
            return $this->redirectToRoute('app_utilisateur');
        }

        return $this->renderForm('utilisateur/index.html.twig', [
            'utilisateurInfos' => $utilisateur,
            'formulaire' => $form,
            'data' => $data,
            'reservations' => $reservations,
            'professionels' => $professionels
        ]);
    }
}

templates/utilisateur/index.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
	{# Media Queries pour la page d'acceuil #}
	{{parent()}}
	<link rel="stylesheet" href="/assets/media-queries-utilisateur.css">
{% endblock %}

{% block title %}
	Hello UtilisateurController!
{% endblock %}

{% block body %}
	{# <h1>id={{id}}</h1> #}
	<div class="container">

		<div class="d-flex  mt-4">
			<div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
				<button class="nav-link active mb-4" id="v-pills-profile-tab" data-bs-toggle="pill" data-bs-target="#v-pills-profile" type="button" role="tab" aria-controls="v-pills-profile" aria-selected="false">
					<i class="fa fa-solid fa-user fa-7x"></i>
				</button>
				<button class="nav-link mb-4" id="v-pills-calendar-tab" data-bs-toggle="pill" data-bs-target="#v-pills-calendar" type="button" role="tab" aria-controls="v-pills-calendar" aria-selected="false">
					<i class="fas fa-calendar-alt fa-7x"></i>
				</button>
				<button class="nav-link mb-4" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" role="tab" aria-controls="v-pills-settings" aria-selected="false">
					<i class="fas fa-history fa-7x"></i>
				</button>
			</div>
			<div class="tab-content" id="v-pills-tabContent">
				<div class="tab-pane fade show active" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
					<div class="container mt-5">
						{% for message in app.flashes('success') %}
						<div class="alert alert-success alert-dismissible fade show" role="alert">
						{{ message }}
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
						</div>
						{% endfor %}
						{{ form_start(formulaire) }}
						<ul class="list-group">
							<div class="row justify-content-evenly gy-3">
								<div class="col-5">
									<li class="list-group-item">
										{{ form_label(formulaire.firstname, null, {'label_attr': {'class': 'form-label'}}) }}
										{{ form_widget(formulaire.firstname, { attr: { class: 'form-control', placeholder: 'Firstname' } }) }}
									</li>
								</div>
								<div class="col-5">
									<li class="list-group-item">
										{{ form_label(formulaire.lastname, 'Nom', {'label_attr': {'class': 'form-label'}}) }}
										{{ form_widget(formulaire.lastname, { attr: { class: 'form-control', placeholder: 'Lastname' } }) }}
									</li>
								</div>
								<div class="col-5">
									<li class="list-group-item">
										{{ form_label(formulaire.email, 'Email', {'label_attr': {'class': 'form-label'}}) }}
										{{ form_widget(formulaire.email, { attr: { class: 'form-control', placeholder: 'Email address' } }) }}
									</li>
								</div>
								<div class="col-5">
									<li class="list-group-item">
										{{ form_label(formulaire.adresse, 'Adresse', {'label_attr': {'class': 'form-label'}}) }}
										{{ form_widget(formulaire.adresse, { attr: { class: 'form-control', placeholder: 'Adresse' } }) }}
									</li>
								</div>
								<div class="col-5">
									<li class="list-group-item">
										{{ form_label(formulaire.date_de_naissance, 'Date de naissance', {'label_attr': {'class': 'form-label'}}) }}
										{{ form_widget(formulaire.date_de_naissance, { attr: { class: 'form-control', placeholder: 'Date de naissance' } }) }}
									</li>
								</div>
								<div class="col-5 gy-4">
									<div class="d-flex justify-content-between">
										<div class="fs-3 d-flex align-items-center">
											{% for personne in formulaire.genre.children %}
												{{ form_widget(personne, { attr: { class: 'form-check-input me-2 mt-1' } }) }}
												{{ form_label(personne, null, {'label_attr': {'class': 'form-check-label pe-4' }})}}
											{% endfor %}
										</div>
									</div>
								</div>
								<div class="col-5">
									{{ form_errors(formulaire.password.first) }}
									<li class="list-group-item">{{ form_widget(formulaire.password.first, { attr: { class: 'form-control', placeholder: 'Modifier le mot de passe' } }) }}</li>
								</div>
								<div class="col-5">
									{{ form_errors(formulaire.password.first) }}
									<li class="list-group-item">
										{{ form_widget(formulaire.password.second, { attr: { class: 'form-control', placeholder: 'Confirmer le mot de passe' } }) }}
										{# <input type="password" name="" id="" class="form-control" placeholder="Confirmer le mot de passe" /> #}
									</li>
								</div>
								<div class="col-5">
									<div class="input-group">
										{{ form_label(formulaire.code_postal, 'Code postal', {label_attr: {'class': 'input-group-text'}}) }}
										{{ form_widget(formulaire.code_postal, { attr: { class: 'form-control', placeholder: 'Code postal' } }) }}
									</div>
								</div>
								<div class="col-5">
									<div class="input-group">
										{{form_label(formulaire.ville, 'Ville', {label_attr: {'class': 'input-group-text'}}) }}
										{{ form_widget(formulaire.ville, { attr: { class: 'form-control', placeholder: 'Ville' } }) }}
									</div>
								</div>
								<div class="col-10">
									<div class="form-check form-switch">
										{{ form_widget(formulaire.alerteSMS, { attr: { class: 'form-check-input' } }) }}
										{{ form_label(formulaire.alerteSMS) }}
										{# <input type="checkbox" id="flexSwitchCheckDefault" class="form-check-input" />
																													<label class="form-check-label" for="flexSwitchCheckDefault">Recevoir les alertes SMS</label> #}
									</div>
									<div class="form-check form-switch">
										{{ form_widget(formulaire.promotions, { attr: { class: 'form-check-input' } }) }}
										{{ form_label(formulaire.promotions) }}
									{# <input type="checkbox" id="flexSwitchCheckDefault" class="form-check-input" /> #}
										{# <label class="form-check-label" for="flexSwitchCheckDefault">Recevoir les messages promotionnels</label> #}
									</div>
								</div>
							</div>
						</ul>
						<div class="row justify-content-center">
							<div class="d-grid col-6 mx-auto col-lg-2">
								<button type="submit" class="btn btn-outline-primary">Enregistrer</button>
							</div>
						</div>
						{{ form_end(formulaire) }}
					</div>
				</div>
				<div class="tab-pane fade" id="v-pills-calendar" role="tabpanel" aria-labelledby="v-pills-calendar-tab">
					<table class="table">
						<thead>
							<tr>
								<th scope="col">Heure de rendez-vous</th>
								<th scope="col">Coiffeur</th>
								<th scope="col">Status</th>
								<th scope="col">Prestations</th>
								{% if is_granted('ROLE_PRO') %}
									<th scope="col">
										<button type="submit" class="btn btn-primary">Enregistrer</button>
									</th>
								{% endif %}
							</tr>
						</thead>
						<tbody>
							{% if is_granted('ROLE_PRO') %}
								{% for professionel in professionels %}
									<tr>
										<th scope="row">{{professionel.HeureDeRendezVous|date("d/m/Y à H\\hi")}}</th>
										<td>{{professionel.idClient}}</td>
										<td>{{professionel.status}}</td>
										{# <td><option {% if professionel.status is  %}{% endif %}></option></td> #}
										<td>{{professionel.prestation}}</td>
										<td></td>
									</tr>
								{% endfor %}
							{% endif %}
							{% for reservation in reservations %}
								<tr>
									<th scope="row">{{reservation.HeureDeRendezVous|date("d/m/Y à H\\hi")}}</th>
									<td>{{reservation.pro}}</td>
									<td>{{reservation.status}}</td>
									<td>{{reservation.prestation}}</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
				<div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
					<div class="form-group">
						<label for="" class="control-label">Commandes</label>
						<div class="alert alert-warning">Aucune Commande</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block javascripts %}
	{# <script>
				document.addEventListener('DOMContentLoaded', function () {
		var calendarEl = document.getElementById('calendar');
		var calendar = new FullCalendar.Calendar(calendarEl, {
		themeSystem: 'bootstrap5',
		locale: 'fr',
		timeZone: 'Europe/Paris',
		headerToolbar: {
			start: 'prev,next today',
			center: 'title',
			end: 'dayGridMonth,timeGridWeek'
		},
		events: {{ data|raw }}
		});
		calendar.render();
		});
			</script> #}
{% endblock %}